repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-check
    args: [--preview, --select=CPY]
  - id: ruff-format
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.6.0
  hooks:
    - id: pyproject-fmt
- repo: https://github.com/biomejs/pre-commit
  rev: v2.2.3
  hooks:
  - id: biome-format
- repo: https://github.com/kynan/nbstripout
  rev: "0.8.1"
  hooks:
    - id: nbstripout
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive]
    additional_dependencies:
    - pytest
    - jupyter-client
    - pytest-subprocess
